version: '3.8'

services:
  warp-website-1:
    image: caomingjun/warp
    container_name: warp-website-1
    ports:
      - "41000:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-2:
    image: caomingjun/warp
    container_name: warp-website-2
    ports:
      - "41001:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-3:
    image: caomingjun/warp
    container_name: warp-website-3
    ports:
      - "41002:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-4:
    image: caomingjun/warp
    container_name: warp-website-4
    ports:
      - "41003:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-5:
    image: caomingjun/warp
    container_name: warp-website-5
    ports:
      - "41004:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-6:
    image: caomingjun/warp
    container_name: warp-website-6
    ports:
      - "41005:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-7:
    image: caomingjun/warp
    container_name: warp-website-7
    ports:
      - "41006:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-8:
    image: caomingjun/warp
    container_name: warp-website-8
    ports:
      - "41007:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-9:
    image: caomingjun/warp
    container_name: warp-website-9
    ports:
      - "41008:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-10:
    image: caomingjun/warp
    container_name: warp-website-10
    ports:
      - "41009:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-11:
    image: caomingjun/warp
    container_name: warp-website-11
    ports:
      - "41010:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-12:
    image: caomingjun/warp
    container_name: warp-website-12
    ports:
      - "41011:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-13:
    image: caomingjun/warp
    container_name: warp-website-13
    ports:
      - "41012:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-14:
    image: caomingjun/warp
    container_name: warp-website-14
    ports:
      - "41013:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-15:
    image: caomingjun/warp
    container_name: warp-website-15
    ports:
      - "41014:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-16:
    image: caomingjun/warp
    container_name: warp-website-16
    ports:
      - "41015:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-17:
    image: caomingjun/warp
    container_name: warp-website-17
    ports:
      - "41016:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-18:
    image: caomingjun/warp
    container_name: warp-website-18
    ports:
      - "41017:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-19:
    image: caomingjun/warp
    container_name: warp-website-19
    ports:
      - "41018:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-20:
    image: caomingjun/warp
    container_name: warp-website-20
    ports:
      - "41019:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-21:
    image: caomingjun/warp
    container_name: warp-website-21
    ports:
      - "41020:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-22:
    image: caomingjun/warp
    container_name: warp-website-22
    ports:
      - "41021:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-23:
    image: caomingjun/warp
    container_name: warp-website-23
    ports:
      - "41022:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-24:
    image: caomingjun/warp
    container_name: warp-website-24
    ports:
      - "41023:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-25:
    image: caomingjun/warp
    container_name: warp-website-25
    ports:
      - "41024:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-26:
    image: caomingjun/warp
    container_name: warp-website-26
    ports:
      - "41025:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-27:
    image: caomingjun/warp
    container_name: warp-website-27
    ports:
      - "41026:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-28:
    image: caomingjun/warp
    container_name: warp-website-28
    ports:
      - "41027:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-29:
    image: caomingjun/warp
    container_name: warp-website-29
    ports:
      - "41028:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-30:
    image: caomingjun/warp
    container_name: warp-website-30
    ports:
      - "41029:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-31:
    image: caomingjun/warp
    container_name: warp-website-31
    ports:
      - "41030:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-32:
    image: caomingjun/warp
    container_name: warp-website-32
    ports:
      - "41031:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-33:
    image: caomingjun/warp
    container_name: warp-website-33
    ports:
      - "41032:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-34:
    image: caomingjun/warp
    container_name: warp-website-34
    ports:
      - "41033:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-35:
    image: caomingjun/warp
    container_name: warp-website-35
    ports:
      - "41034:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-36:
    image: caomingjun/warp
    container_name: warp-website-36
    ports:
      - "41035:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-37:
    image: caomingjun/warp
    container_name: warp-website-37
    ports:
      - "41036:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-38:
    image: caomingjun/warp
    container_name: warp-website-38
    ports:
      - "41037:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-39:
    image: caomingjun/warp
    container_name: warp-website-39
    ports:
      - "41038:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-40:
    image: caomingjun/warp
    container_name: warp-website-40
    ports:
      - "41039:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-41:
    image: caomingjun/warp
    container_name: warp-website-41
    ports:
      - "41040:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-42:
    image: caomingjun/warp
    container_name: warp-website-42
    ports:
      - "41041:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-43:
    image: caomingjun/warp
    container_name: warp-website-43
    ports:
      - "41042:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-44:
    image: caomingjun/warp
    container_name: warp-website-44
    ports:
      - "41043:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-45:
    image: caomingjun/warp
    container_name: warp-website-45
    ports:
      - "41044:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-46:
    image: caomingjun/warp
    container_name: warp-website-46
    ports:
      - "41045:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-47:
    image: caomingjun/warp
    container_name: warp-website-47
    ports:
      - "41046:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-48:
    image: caomingjun/warp
    container_name: warp-website-48
    ports:
      - "41047:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-49:
    image: caomingjun/warp
    container_name: warp-website-49
    ports:
      - "41048:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always

  warp-website-50:
    image: caomingjun/warp
    container_name: warp-website-50
    ports:
      - "41049:1080"
    environment:
      - WARP_SLEEP=2
    privileged: true
    restart: always
